### ISSUE TITLE
NBU Exchange Rates doesn't retrieve rates

### ISSUE THREAD

**Issue by Plastikkboy** [andriisem/addons#2]
NBU Exchange Rates doesn't retrieve rates on the Odoo 13  with following error message: `
`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connection.py", line 355, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.6/ssl.py", line 900, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.6/ssl.py", line 864, in _check_connected
    self.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/urllib3/connection.py", line 355, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.6/ssl.py", line 900, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.6/ssl.py", line 864, in _check_connected
    self.getpeername()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 411, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 398, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo-custom-addons/res_currency_nbu/models/res_currency.py", line 36, in action_parse_nbu_rates
    self._parse_nbu_rates()
  File "/opt/odoo13/odoo-custom-addons/res_currency_nbu/models/res_currency.py", line 18, in _parse_nbu_rates
    rates_dict = get_rates_by_code(curr_codes)
  File "/opt/odoo13/odoo-custom-addons/res_currency_nbu/utils/parse_rates.py", line 30, in get_rates_by_code
    rates_json = _get_rates_in_json()
  File "/opt/odoo13/odoo-custom-addons/res_currency_nbu/utils/parse_rates.py", line 13, in _get_rates_in_json
    data = requests.get(NBU_RATES_URL_JSON)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))`

I have this message twice after hitting "Update Currency" button. After the third hit it loads the exchange rate.
Any suggestion? Thank you!

**Comment by Plastikkboy** [comment]
But it still doesn't work :( I have to click the "Update" button triple to have an updated rate. Twice with error and the third time is successful. Any suggest?
